# Best Practices for Writing Docker Files
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

FROM ubuntu:18.04 

#ENV MAILGUN_API_KEY 
#ENV MAILGUN_EMAIL_ADDRESS
ENV WEBSITE_ORIGINS 'http://localhost'
#ENV SECRET_KEY
ENV REACT_APP_API_ROOT "http://localhost:5000"

RUN apt-get update && apt-get install -y \ 
    curl \
    gnupg \
    git \
    mariadb-server \
    nginx \
    python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
    
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y \
    yarn

RUN git clone https://github.com/consensys-space/trusat-orbit
RUN git clone https://github.com/consensys-space/trusat-backend
WORKDIR trusat-backend/
# Next line, temporary for testing 
RUN git checkout update-readme.rebase.fixes
RUN git clone https://github.com/consensys-space/trusat-frontend

WORKDIR trusat-frontend/
RUN yarn install && yarn build
WORKDIR /trusat-backend 
RUN python3 -m pip install wheel gunicorn
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install -r database_tools/requirements.txt
RUN python3 -m pip install -r ../trusat-orbit/requirements.txt