# Best Practices for Writing Docker Files
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

FROM ubuntu:18.04 

#ENV MAILGUN_API_KEY 
#ENV MAILGUN_EMAIL_ADDRESS
#ENV SECRET_KEY
ENV WEBSITE_ORIGINS 'http://localhost'
ENV REACT_APP_API_ROOT "http://localhost:5000"

ENV DB_HOSTNAME "trusat_dev_mysql"
ENV DB_ROOT_PASSWORD "trusat_mysql_root_password"
ENV DB_NAME "trusat_dev"
ENV DB_USER "devuser"
ENV DB_USER_PASSWORD "dev_password"

RUN apt-get update && apt-get install -y \ 
    curl \
    gnupg \
    git \
    mariadb-client \
    nginx \
    python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
    
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y \
    yarn

RUN git clone https://github.com/TruSat/trusat-orbit
RUN git clone https://github.com/TruSat/trusat-backend
WORKDIR trusat-backend/
RUN git clone https://github.com/TruSat/trusat-frontend

WORKDIR trusat-frontend/
RUN yarn install && yarn build

WORKDIR /trusat-orbit
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install https://github.com/brandon-rhodes/python-sgp4/archive/master.zip
RUN python3 setup.py develop

WORKDIR /trusat-backend 
RUN git checkout dev.chris.package
RUN python3 -m pip install wheel gunicorn
RUN python3 -m pip install -r requirements-database.txt
RUN python3 -m pip install -r requirements-server.txt
RUN python3 -m pip install -r trusat_backend/database_tools/requirements.txt
# For some reason this helps google_email.py run
RUN pip3 install --upgrade google-api-core

RUN mysql --password=${DB_ROOT_PASSWORD} -h ${DB_HOSTNAME} -e  "CREATE DATABASE IF NOT EXISTS ${DB_NAME} DEFAULT CHARACTER SET 'utf8'; \
    USE ${DB_NAME}; \
    CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_USER_PASSWORD}'; \
    GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%'; \
    FLUSH PRIVILEGES;" 

RUN cp trusat-config.yaml ../
RUN python3 create_tables.py
RUN python3 trusat_backend/database_tools/categorize.py
RUN python3 trusat_backend/database_tools/update_SATCAT_UCS_from_source.py

RUN zcat trusat_dev_db.sql.gz | mysql --password=${DB_ROOT_PASSWORD} -h ${DB_HOSTNAME} -f ${DB_NAME}
RUN cp trusat-backend-nginx-dev.conf /etc/nginx/sites-enabled/trusat-backend
EXPOSE 5000

CMD bash -C '/trusat-backend/Docker-entrypoint.sh';'bash'